version: '3.0'
services:
  api:
    container_name: api
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/workspace:cached
      
    
  web:
    container_name: web
    build: 
      context: ./web
      target: base
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:8000/api
    tty: true
    volumes:
      - ./web:/workspace:cached
    depends_on:
      - api
